# Generated by Django 5.2.1 on 2025-05-31 21:16

from django.db import migrations


def normalize_emails_to_lowercase(apps, schema_editor):
    """
    Data migration to convert all existing email addresses to lowercase.
    This ensures case-insensitive email authentication works correctly.
    """
    User = apps.get_model('users', 'User')
    
    # Batch update emails to lowercase
    for user in User.objects.all():
        if user.email:
            lowercase_email = user.email.lower()
            if user.email != lowercase_email:
                user.email = lowercase_email
                user.save(update_fields=['email'])


def reverse_normalize_emails(apps, schema_editor):
    """
    Reverse migration - cannot truly reverse email case normalization
    as we don't store the original case. This is a no-op.
    """
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_user_options_alter_user_managers'),
    ]

    operations = [
        migrations.RunPython(
            normalize_emails_to_lowercase,
            reverse_normalize_emails,
        ),
    ]
