# Generated by Django 5.2.1 on 2025-05-10 15:57

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('questions', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_questions', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='question',
            name='last_updated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='updated_questions', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='mcqchoice',
            name='question',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='choices', to='questions.question'),
        ),
        migrations.AddField(
            model_name='questiontag',
            name='question',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='questions.question'),
        ),
        migrations.AddField(
            model_name='questiontag',
            name='tag',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='questions.tag'),
        ),
        migrations.AddField(
            model_name='question',
            name='tags',
            field=models.ManyToManyField(related_name='questions', through='questions.QuestionTag', to='questions.tag'),
        ),
        migrations.AddField(
            model_name='topic',
            name='parent_topic',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='child_topics', to='questions.topic'),
        ),
        migrations.AddField(
            model_name='question',
            name='topic',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='questions', to='questions.topic'),
        ),
        migrations.AddIndex(
            model_name='mcqchoice',
            index=models.Index(fields=['question', 'display_order'], name='questions_m_questio_8972bc_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='questiontag',
            unique_together={('question', 'tag')},
        ),
        migrations.AddIndex(
            model_name='topic',
            index=models.Index(fields=['parent_topic', 'display_order'], name='questions_t_parent__0b3464_idx'),
        ),
        migrations.AddIndex(
            model_name='question',
            index=models.Index(fields=['topic', 'question_type', 'difficulty', 'is_active'], name='questions_q_topic_i_03c5ed_idx'),
        ),
    ]
