# Generated by Django 5.2.1 on 2025-05-14 16:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0003_add_exam_field'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='question',
            new_name='questions_q_exam_id_10e613_idx',
            old_name='questions_q_exam_id_a4b3e5_idx',
        ),
    ]
