# Generated by Django 5.2.1 on 2025-05-25 05:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0004_rename_questions_q_exam_id_a4b3e5_idx_questions_q_exam_id_10e613_idx'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='question',
            options={'ordering': ['-created_at']},
        ),
    ]
