# Generated by Django 5.2.1 on 2025-05-29 16:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0005_alter_question_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mcqchoice',
            name='question',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mcqchoice_set', to='questions.question'),
        ),
    ]
