# Generated by Django 5.2.1 on 2025-05-10 15:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ExamSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=255, null=True)),
                ('session_type', models.CharField(choices=[('PRACTICE', 'Practice'), ('TIMED_EXAM', 'Timed Exam'), ('ASSESSMENT', 'Assessment')], db_index=True, max_length=20)),
                ('start_time', models.DateTimeField(db_index=True)),
                ('end_time_expected', models.DateTimeField()),
                ('actual_end_time', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(choices=[('IN_PROGRESS', 'In Progress'), ('COMPLETED', 'Completed'), ('ABANDONED', 'Abandoned')], db_index=True, max_length=20)),
                ('total_score_achieved', models.FloatField(blank=True, null=True)),
                ('total_possible_score', models.FloatField()),
                ('pass_threshold', models.FloatField()),
                ('passed', models.BooleanField(blank=True, null=True)),
                ('time_limit_seconds', models.IntegerField()),
                ('metadata', models.JSONField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'assessment_examsession',
            },
        ),
        migrations.CreateModel(
            name='ExamSessionQuestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('display_order', models.IntegerField(default=0)),
                ('question_weight', models.FloatField(default=1.0)),
            ],
            options={
                'db_table': 'assessment_examsession_questions',
            },
        ),
        migrations.CreateModel(
            name='UserAnswer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('submitted_answer_text', models.TextField(blank=True, null=True)),
                ('submitted_calculation_input', models.JSONField(blank=True, null=True)),
                ('raw_score', models.FloatField(blank=True, null=True)),
                ('weighted_score', models.FloatField(blank=True, null=True)),
                ('max_possible_score', models.FloatField()),
                ('is_correct', models.BooleanField(blank=True, null=True)),
                ('ai_feedback', models.TextField(blank=True, null=True)),
                ('human_feedback', models.TextField(blank=True, null=True)),
                ('evaluation_status', models.CharField(choices=[('PENDING', 'Pending'), ('EVALUATED', 'Evaluated'), ('ERROR', 'Error'), ('MCQ_SCORED', 'MCQ Scored')], db_index=True, max_length=20)),
                ('time_spent_seconds', models.IntegerField(blank=True, null=True)),
                ('submission_time', models.DateTimeField(db_index=True)),
                ('retry_count', models.IntegerField(default=0)),
            ],
            options={
                'db_table': 'assessment_useranswer',
            },
        ),
        migrations.CreateModel(
            name='UserAnswerMCQChoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'db_table': 'assessment_useranswer_mcq_choices',
            },
        ),
    ]
