# Generated by Django 5.2.1 on 2025-05-10 15:57

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('assessment', '0001_initial'),
        ('questions', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='examsession',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exam_sessions', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='examsessionquestion',
            name='exam_session',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='assessment.examsession'),
        ),
        migrations.AddField(
            model_name='examsessionquestion',
            name='question',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='questions.question'),
        ),
        migrations.AddField(
            model_name='examsession',
            name='questions',
            field=models.ManyToManyField(through='assessment.ExamSessionQuestion', to='questions.question'),
        ),
        migrations.AddField(
            model_name='useranswer',
            name='exam_session',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='user_answers', to='assessment.examsession'),
        ),
        migrations.AddField(
            model_name='useranswer',
            name='question',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='user_answers', to='questions.question'),
        ),
        migrations.AddField(
            model_name='useranswer',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answers', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='useranswermcqchoice',
            name='mcq_choice',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='questions.mcqchoice'),
        ),
        migrations.AddField(
            model_name='useranswermcqchoice',
            name='user_answer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='assessment.useranswer'),
        ),
        migrations.AddField(
            model_name='useranswer',
            name='mcq_choices',
            field=models.ManyToManyField(through='assessment.UserAnswerMCQChoice', to='questions.mcqchoice'),
        ),
        migrations.AddIndex(
            model_name='examsessionquestion',
            index=models.Index(fields=['exam_session', 'display_order'], name='assessment__exam_se_34906b_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='examsessionquestion',
            unique_together={('exam_session', 'question')},
        ),
        migrations.AddIndex(
            model_name='examsession',
            index=models.Index(fields=['user', 'status', 'start_time'], name='assessment__user_id_1fb4dc_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='useranswermcqchoice',
            unique_together={('user_answer', 'mcq_choice')},
        ),
        migrations.AddIndex(
            model_name='useranswer',
            index=models.Index(fields=['user', 'question', 'submission_time'], name='assessment__user_id_15d133_idx'),
        ),
        migrations.AddIndex(
            model_name='useranswer',
            index=models.Index(fields=['exam_session', 'evaluation_status'], name='assessment__exam_se_d84db5_idx'),
        ),
    ]
