# Generated by Django 5.2.1 on 2025-05-14 16:27

import assessment.models
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assessment', '0002_initial'),
        ('exams', '0001_initial'),
        ('questions', '0004_rename_questions_q_exam_id_a4b3e5_idx_questions_q_exam_id_10e613_idx'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='examsession',
            name='exam',
            field=models.ForeignKey(default=assessment.models.ExamSession.get_default_exam, help_text='The exam or category this session belongs to.', on_delete=django.db.models.deletion.PROTECT, related_name='exam_sessions', to='exams.exam'),
        ),
        migrations.AddIndex(
            model_name='examsession',
            index=models.Index(fields=['exam', 'user'], name='assessment__exam_id_9a1f1b_idx'),
        ),
    ]
