# Generated by Django 5.2.1 on 2025-05-30 12:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assessment', '0004_learningmaterial_examsession_evaluation_mode_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='useranswer',
            name='metadata',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='useranswer',
            name='evaluation_status',
            field=models.CharField(choices=[('PENDING', 'Pending'), ('EVALUATED', 'Evaluated'), ('ERROR', 'Error'), ('MCQ_SCORED', 'MCQ Scored'), ('NOT_APPLICABLE', 'Not Applicable')], db_index=True, max_length=20),
        ),
    ]
