# Generated by Django 5.2.1 on 2025-05-10 15:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='StudySession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_time', models.DateTimeField()),
                ('end_time', models.DateTimeField()),
                ('topics_studied', models.JSONField()),
                ('questions_answered', models.IntegerField()),
                ('correct_answers', models.IntegerField()),
                ('device_info', models.CharField(blank=True, max_length=255, null=True)),
                ('session_source', models.CharField(choices=[('WEB', 'Web'), ('ANDROID', 'Android'), ('IOS', 'iOS')], max_length=10)),
            ],
            options={
                'db_table': 'analytics_studysession',
            },
        ),
        migrations.CreateModel(
            name='UserPerformanceRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_type', models.CharField(blank=True, db_index=True, max_length=20, null=True)),
                ('difficulty', models.CharField(blank=True, max_length=10, null=True)),
                ('date_recorded', models.DateField(db_index=True)),
                ('questions_answered', models.IntegerField(default=0)),
                ('correct_answers', models.IntegerField(default=0)),
                ('partially_correct_answers', models.IntegerField(default=0)),
                ('total_points_earned', models.FloatField(default=0)),
                ('total_points_possible', models.FloatField(default=0)),
                ('total_time_spent_seconds', models.IntegerField(default=0)),
                ('accuracy', models.FloatField(blank=True, null=True)),
                ('average_time_per_question', models.FloatField(blank=True, null=True)),
            ],
            options={
                'db_table': 'analytics_userperformancerecord',
            },
        ),
        migrations.CreateModel(
            name='UserProgress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_questions_in_topic', models.IntegerField()),
                ('questions_attempted', models.IntegerField(default=0)),
                ('questions_mastered', models.IntegerField(default=0)),
                ('proficiency_level', models.CharField(choices=[('BEGINNER', 'Beginner'), ('INTERMEDIATE', 'Intermediate'), ('ADVANCED', 'Advanced'), ('EXPERT', 'Expert')], max_length=20)),
                ('last_activity_date', models.DateTimeField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'analytics_userprogress',
            },
        ),
    ]
