# Generated by Django 5.2.1 on 2025-05-27 02:57

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('affiliates', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AffiliatePlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text="Plan name (e.g., 'Influencer Basic', 'Premium Partner')", max_length=100)),
                ('description', models.TextField(help_text='Description of what this plan offers')),
                ('plan_type', models.CharField(choices=[('PURE_AFFILIATE', 'Pure Affiliate (Commission only)'), ('FIXED_PLUS_COMMISSION', 'Fixed Payment + Commission'), ('TIERED_COMMISSION', 'Tiered Commission')], max_length=25)),
                ('commission_per_download', models.DecimalField(decimal_places=2, default=0.0, help_text='Fixed amount per download/signup (in EUR)', max_digits=10)),
                ('commission_per_subscription', models.DecimalField(decimal_places=2, default=0.0, help_text='Fixed amount per successful subscription (in EUR)', max_digits=10)),
                ('commission_percentage', models.DecimalField(decimal_places=2, default=0.0, help_text='Percentage of subscription value (0-100)', max_digits=5)),
                ('fixed_monthly_payment', models.DecimalField(decimal_places=2, default=0.0, help_text='Fixed monthly payment (in EUR)', max_digits=10)),
                ('tier_settings', models.JSONField(blank=True, help_text='Tiered commission settings in JSON format', null=True)),
                ('minimum_followers', models.PositiveIntegerField(default=0, help_text='Minimum followers required for this plan')),
                ('minimum_monthly_conversions', models.PositiveIntegerField(default=0, help_text='Minimum monthly conversions to maintain this plan')),
                ('is_active', models.BooleanField(default=True)),
                ('is_auto_approval', models.BooleanField(default=False, help_text='Whether applications for this plan are auto-approved')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='AffiliateApplication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('business_name', models.CharField(blank=True, max_length=200, null=True)),
                ('website_url', models.URLField(blank=True, null=True)),
                ('social_media_links', models.JSONField(blank=True, help_text='Social media profiles in JSON format', null=True)),
                ('audience_description', models.TextField(help_text='Description of audience and reach')),
                ('promotion_strategy', models.TextField(help_text='How they plan to promote the platform')),
                ('follower_count', models.PositiveIntegerField(default=0, help_text='Total follower count across platforms')),
                ('status', models.CharField(choices=[('PENDING', 'Pending Review'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected'), ('UNDER_REVIEW', 'Under Review')], default='PENDING', max_length=20)),
                ('admin_notes', models.TextField(blank=True, null=True)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_affiliate_applications', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='affiliate_applications', to=settings.AUTH_USER_MODEL)),
                ('requested_plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='applications', to='affiliates.affiliateplan')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='affiliate',
            name='affiliate_plan',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='affiliates', to='affiliates.affiliateplan'),
        ),
    ]
