# Generated by Django 5.2.1 on 2025-05-10 15:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AIContentAlert',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('alert_type', models.CharField(choices=[('TOPIC_UPDATE', 'Topic Update'), ('QUESTION_UPDATE_SUGGESTION', 'Question Update Suggestion')], db_index=True, max_length=30)),
                ('summary_of_potential_change', models.TextField()),
                ('detailed_explanation', models.TextField(blank=True, null=True)),
                ('source_urls', models.JSONField(blank=True, null=True)),
                ('ai_confidence_score', models.FloatField(blank=True, null=True)),
                ('priority', models.CharField(choices=[('LOW', 'Low'), ('MEDIUM', 'Medium'), ('HIGH', 'High')], db_index=True, default='MEDIUM', max_length=10)),
                ('status', models.CharField(choices=[('NEW', 'New'), ('UNDER_REVIEW', 'Under Review'), ('ACTION_TAKEN', 'Action Taken'), ('DISMISSED', 'Dismissed')], db_index=True, default='NEW', max_length=20)),
                ('admin_notes', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('action_taken', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'ai_integration_aicontentalert',
            },
        ),
        migrations.CreateModel(
            name='AIEvaluationLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prompt_used', models.TextField()),
                ('ai_response', models.TextField()),
                ('processing_time_ms', models.IntegerField()),
                ('success', models.BooleanField()),
                ('error_message', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'ai_integration_aievaluationlog',
            },
        ),
        migrations.CreateModel(
            name='AIFeedbackTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('template_name', models.CharField(max_length=100, unique=True)),
                ('question_type', models.CharField(choices=[('OPEN_ENDED', 'Open Ended Question'), ('CALCULATION', 'Calculation Question')], max_length=20)),
                ('template_content', models.TextField()),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'ai_integration_aifeedbacktemplate',
            },
        ),
    ]
