# Generated by Django 5.2.1 on 2025-05-21 21:51

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ai_integration', '0003_initial'),
        ('exams', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ChatbotConversation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=200, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chatbot_conversations', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Chatbot Conversation',
                'verbose_name_plural': 'Chatbot Conversations',
                'db_table': 'ai_integration_chatbotconversation',
            },
        ),
        migrations.CreateModel(
            name='ChatbotMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('USER', 'User'), ('ASSISTANT', 'Assistant'), ('SYSTEM', 'System')], max_length=10)),
                ('content', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('processing_time_ms', models.IntegerField(blank=True, null=True)),
                ('conversation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='ai_integration.chatbotconversation')),
            ],
            options={
                'verbose_name': 'Chatbot Message',
                'verbose_name_plural': 'Chatbot Messages',
                'db_table': 'ai_integration_chatbotmessage',
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='ContentUpdateScanConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('frequency', models.CharField(choices=[('DAILY', 'Daily'), ('WEEKLY', 'Weekly'), ('MONTHLY', 'Monthly'), ('QUARTERLY', 'Quarterly')], default='WEEKLY', max_length=10)),
                ('max_questions_per_scan', models.IntegerField(default=20, help_text='Maximum number of questions to check per scan')),
                ('is_active', models.BooleanField(default=True)),
                ('prompt_template', models.TextField(help_text='Template for the AI prompt')),
                ('last_run', models.DateTimeField(blank=True, null=True)),
                ('next_scheduled_run', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_scan_configs', to=settings.AUTH_USER_MODEL)),
                ('exams', models.ManyToManyField(related_name='content_update_configs', to='exams.exam')),
            ],
            options={
                'verbose_name': 'Content Update Scan Configuration',
                'verbose_name_plural': 'Content Update Scan Configurations',
                'db_table': 'ai_integration_contentupdatescanconfig',
            },
        ),
        migrations.CreateModel(
            name='ContentUpdateScanLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_time', models.DateTimeField()),
                ('end_time', models.DateTimeField(blank=True, null=True)),
                ('topics_scanned', models.JSONField(blank=True, null=True)),
                ('questions_scanned', models.IntegerField(default=0)),
                ('alerts_generated', models.IntegerField(default=0)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('IN_PROGRESS', 'In Progress'), ('COMPLETED', 'Completed'), ('FAILED', 'Failed')], default='PENDING', max_length=20)),
                ('error_message', models.TextField(blank=True, null=True)),
                ('scan_config', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scan_logs', to='ai_integration.contentupdatescanconfig')),
            ],
            options={
                'verbose_name': 'Content Update Scan Log',
                'verbose_name_plural': 'Content Update Scan Logs',
                'db_table': 'ai_integration_contentupdatescanlog',
            },
        ),
    ]
