# Generated by Django 5.2.1 on 2025-05-14 16:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Exam',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
                ('slug', models.SlugField(max_length=255, unique=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('is_active', models.BooleanField(db_index=True, default=True, help_text='Whether this exam or category is currently active and available.')),
                ('display_order', models.IntegerField(default=0, help_text='Order in which exams/categories are displayed.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('parent_exam', models.ForeignKey(blank=True, help_text='For creating a hierarchy of exams, categories, or subjects.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sub_exams', to='exams.exam')),
            ],
            options={
                'db_table': 'exams_exam',
                'indexes': [models.Index(fields=['parent_exam', 'display_order'], name='exams_exam_parent__2a373b_idx')],
            },
        ),
    ]
