# Generated by Django 5.2.1 on 2025-05-31 22:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exams', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExamTranslation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('language_code', models.CharField(help_text="Language code (e.g., 'de', 'fr', 'es')", max_length=10)),
                ('translated_description', models.TextField(help_text='Translated description of the exam')),
                ('translation_status', models.CharField(choices=[('PENDING', 'Pending Translation'), ('COMPLETED', 'Translation Completed'), ('ERROR', 'Translation Error')], default='PENDING', max_length=20)),
                ('translated_at', models.DateTimeField(auto_now_add=True)),
                ('translation_method', models.CharField(choices=[('AI', 'AI Translation'), ('MANUAL', 'Manual Translation')], default='AI', max_length=20)),
                ('exam', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='translations', to='exams.exam')),
            ],
            options={
                'db_table': 'exams_examtranslation',
                'indexes': [models.Index(fields=['exam', 'language_code'], name='exams_examt_exam_id_0341a8_idx'), models.Index(fields=['translation_status'], name='exams_examt_transla_705ef5_idx')],
                'unique_together': {('exam', 'language_code')},
            },
        ),
    ]
