# Generated by Django 5.2.1 on 2025-05-10 15:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('currency', models.CharField(max_length=3)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('SUCCESSFUL', 'Successful'), ('FAILED', 'Failed'), ('REFUNDED', 'Refunded')], db_index=True, max_length=20)),
                ('payment_gateway_transaction_id', models.CharField(max_length=100, unique=True)),
                ('payment_method_details', models.JSONField(blank=True, null=True)),
                ('transaction_time', models.DateTimeField(db_index=True)),
                ('billing_address', models.JSONField(blank=True, null=True)),
                ('invoice_number', models.CharField(blank=True, max_length=50, null=True, unique=True)),
                ('refund_reference', models.CharField(blank=True, max_length=100, null=True)),
                ('metadata', models.JSONField(blank=True, null=True)),
            ],
            options={
                'db_table': 'subscriptions_payment',
            },
        ),
        migrations.CreateModel(
            name='PricingPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('slug', models.SlugField(max_length=100, unique=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('currency', models.CharField(default='USD', max_length=3)),
                ('billing_cycle', models.CharField(choices=[('MONTHLY', 'Monthly'), ('QUARTERLY', 'Quarterly'), ('YEARLY', 'Yearly'), ('ONE_TIME', 'One Time')], max_length=20)),
                ('features_list', models.JSONField()),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('display_order', models.IntegerField(default=0)),
                ('payment_gateway_plan_id', models.CharField(blank=True, max_length=100, null=True, unique=True)),
                ('trial_days', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'subscriptions_pricingplan',
            },
        ),
        migrations.CreateModel(
            name='ReferralProgram',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('description', models.TextField()),
                ('reward_type', models.CharField(choices=[('DISCOUNT_PERCENTAGE', 'Discount Percentage'), ('DISCOUNT_FIXED', 'Discount Fixed Amount'), ('EXTEND_SUBSCRIPTION_DAYS', 'Extend Subscription Days'), ('CREDIT', 'Account Credit')], max_length=30)),
                ('reward_value', models.DecimalField(decimal_places=2, max_digits=10)),
                ('referrer_reward_type', models.CharField(choices=[('DISCOUNT_PERCENTAGE', 'Discount Percentage'), ('DISCOUNT_FIXED', 'Discount Fixed Amount'), ('EXTEND_SUBSCRIPTION_DAYS', 'Extend Subscription Days'), ('CREDIT', 'Account Credit')], max_length=30)),
                ('referrer_reward_value', models.DecimalField(decimal_places=2, max_digits=10)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('valid_from', models.DateField(blank=True, null=True)),
                ('valid_until', models.DateField(blank=True, null=True)),
                ('usage_limit', models.IntegerField(default=0)),
                ('min_purchase_amount', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'subscriptions_referralprogram',
            },
        ),
        migrations.CreateModel(
            name='UserReferral',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('referral_code_used', models.CharField(db_index=True, max_length=50)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('COMPLETED', 'Completed'), ('EXPIRED', 'Expired'), ('INVALID', 'Invalid')], db_index=True, max_length=20)),
                ('reward_granted_to_referrer', models.BooleanField(default=False)),
                ('reward_granted_to_referred', models.BooleanField(default=False)),
                ('date_referred', models.DateTimeField(auto_now_add=True)),
                ('date_completed', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'subscriptions_userreferral',
            },
        ),
        migrations.CreateModel(
            name='UserSubscription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateTimeField(db_index=True)),
                ('end_date', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('status', models.CharField(choices=[('ACTIVE', 'Active'), ('CANCELED', 'Canceled'), ('EXPIRED', 'Expired'), ('PENDING_PAYMENT', 'Pending Payment'), ('GRACE_PERIOD', 'Grace Period')], db_index=True, max_length=20)),
                ('payment_gateway_subscription_id', models.CharField(blank=True, max_length=100, null=True, unique=True)),
                ('auto_renew', models.BooleanField(default=True)),
                ('cancelled_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('renewal_reminder_sent', models.BooleanField(default=False)),
            ],
            options={
                'db_table': 'subscriptions_usersubscription',
            },
        ),
    ]
