# Generated by Django 5.2.1 on 2025-05-14 16:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exams', '0001_initial'),
        ('subscriptions', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='pricingplan',
            name='exam',
            field=models.ForeignKey(blank=True, help_text='The exam or category this pricing plan applies to.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='pricing_plans', to='exams.exam'),
        ),
        migrations.AddIndex(
            model_name='pricingplan',
            index=models.Index(fields=['exam', 'display_order'], name='subscriptio_exam_id_95ff4e_idx'),
        ),
    ]
