# Generated by Django 5.2.1 on 2025-05-14 16:11

import django.db.models.deletion
from django.db import migrations, models


def create_default_exam_and_update_plans(apps, schema_editor):
    Exam = apps.get_model('exams', 'Exam')
    PricingPlan = apps.get_model('subscriptions', 'PricingPlan')
    
    # Create a default exam if it doesn't exist
    default_exam, created = Exam.objects.get_or_create(
        name='Default Exam Category',
        slug='default-exam-category',
        defaults={
            'description': 'Default category for existing pricing plans',
            'is_active': True,
            'display_order': 0
        }
    )
    
    # Update any existing pricing plans with null exam
    PricingPlan.objects.filter(exam__isnull=True).update(exam=default_exam)


class Migration(migrations.Migration):

    dependencies = [
        ('exams', '0001_initial'),
        ('subscriptions', '0003_pricingplan_exam_and_more'),
    ]

    operations = [
        migrations.RunPython(create_default_exam_and_update_plans),
        migrations.AlterField(
            model_name='pricingplan',
            name='exam',
            field=models.ForeignKey(help_text='The exam or category this pricing plan applies to.', on_delete=django.db.models.deletion.PROTECT, related_name='pricing_plans', to='exams.exam'),
        ),
    ]
